version: '3.8'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mysql_petfood
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3r4
      MYSQL_DATABASE: petfood
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: petfood_backend
    depends_on:
      - database
    ports:
      - "5000:5000"
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: q1w2e3r4
      DB_NAME: petfood

volumes:
  db_data:
