import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: "rgb(252,251,247)",
    alignItems: "stretch",
    borderWidth: 5,
    borderRadius: 10,
    borderColor: "rgb(73,160,195)",
  },
  containerLogin: {
    flex: 1,
    minWidth: 300,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    //borderWidth: 5,
    //borderColor: "rgb(73,160,195)",
  },
  container: {
    //flex: 1,
    //minWidth: 300,
    //justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    //borderWidth: 2,
    //borderColor: "rgb(73,160,195)",
  },
  scrollView: {
    flex: 1,
    //backgroundColor: "rgb(252,251,247)",
    //justifyContent: "center",
    alignItems: "center",
    //borderWidth: 2,
    //borderColor: "rgb(73,160,195)",
    //minWidth: 300,
  },
  scrollSelect: {
    //backgroundColor: "rgb(252,251,247)",
    //justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    padding: 20,
    borderColor: "rgb(73,160,195)",
    minWidth: 300,
  },
  container2: {
    alignItems: "stretch",
  },
  bigLogo: {
    fontFamily: "Courier",
    fontSize: 40,
    fontWeight: "bold",
    fontStyle: "italic",
    textAlign: "center",
    marginBottom: 30,
    color: "rgb(123, 64, 26)",
  },
  smallLogo: {
    fontFamily: "Courier",
    fontSize: 20,
    fontWeight: "bold",
    fontStyle: "italic",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 30,
    color: "rgb(123, 64, 26)",
  },
  inputBig: {
    borderWidth: 1,
    borderColor: "rgb(222,169,61)",
    borderRadius: 5,
    backgroundColor: "#fff",
    marginBottom: 20,
    padding: 10,
    fontSize: 16,
    fontColor: "rgb(170,170,170)",
    minWidth: 250,
  },
  inputSmall: {
    minWidth: 250,
    borderWidth: 1,
    borderColor: "rgb(222,169,61)",
    borderRadius: 5,
    backgroundColor: "#fff",
    margin: 7,
    padding: 5,
    fontSize: 12,
    fontColor: "rgb(170,170,170)",
  },
  button: {
    backgroundColor: "rgb(126,186,75)",
    padding: 7,
    width: 120,
    borderRadius: 10,
    alignItems: "center",
    margin: 10,
  },
  buttonAttent: {
    borderWidth: 1,
    borderColor: "rgb(240,0,0)",
    backgroundColor: "#fff",
    padding: 7,
    width: 120,
    borderRadius: 10,
    alignItems: "center",
    margin: 10,
  },
  buttonInvis: {
    borderRadius: 15,
    alignItems: "center",
    marginTop: 25,
  },
  buttonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },
  buttonAttentText: {
    color: "rgb(240,0,0)",
    fontSize: 14,
    //fontWeight: "bold",
  },
  buttonInvisText: {
    color: "rgb(90,90,90)",
    fontSize: 12,
    fontWeight: "bold",
    margin: 10,
  },
  label: {
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 10,
    marginBottom: 5,
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    margin: 5,
    fontFamily: "Courier",
    fontStyle: "italic",
  },
  loginLink: {
    marginTop: 20,
    alignItems: "center",
  },
  switchContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    margin: 3,
  },
  petImg: {
    width: 100,
    height: 100,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "rgb(222,169,61)",
    borderRadius: 30,
    marginBottom: 10,
  },
  picker: {
    height: 25,
    width: 250,
    borderWidth: 1,
    borderColor: "rgb(222,169,61)",
    backgroundColor: "#fff",
    margin: 7,
    fontSize: 12,
  },
  radio: {
    layout: "row",
    borderColor: "#0f0",
    borderSize: 1,
    color: "#f00",
    size: 100,
    fontSize: 20,
  },
  radioText: {
    fontSize: 14,
    color: "#444",
  },
});

export default styles;
